//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18408.
// 
#pragma warning disable 1591

namespace POS.Admin.Appl.WSPOS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="posserviceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ObjParameters[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Parameters[]))]
    public partial class posservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback setTransactionsArrayOperationCompleted;
        
        private System.Threading.SendOrPostCallback setImageOperationCompleted;
        
        private System.Threading.SendOrPostCallback cleanImageOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public posservice() {
            this.Url = global::POS.Admin.Appl.Properties.Settings.Default.POS_Admin_Appl_WSPOS_posservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event setTransactionsArrayCompletedEventHandler setTransactionsArrayCompleted;
        
        /// <remarks/>
        public event setImageCompletedEventHandler setImageCompleted;
        
        /// <remarks/>
        public event cleanImageCompletedEventHandler cleanImageCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setTransactionsArray", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable setTransactionsArray(TransactionDb transactionDb, ArrayParameters arrayParameters) {
            object[] results = this.Invoke("setTransactionsArray", new object[] {
                        transactionDb,
                        arrayParameters});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void setTransactionsArrayAsync(TransactionDb transactionDb, ArrayParameters arrayParameters) {
            this.setTransactionsArrayAsync(transactionDb, arrayParameters, null);
        }
        
        /// <remarks/>
        public void setTransactionsArrayAsync(TransactionDb transactionDb, ArrayParameters arrayParameters, object userState) {
            if ((this.setTransactionsArrayOperationCompleted == null)) {
                this.setTransactionsArrayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetTransactionsArrayOperationCompleted);
            }
            this.InvokeAsync("setTransactionsArray", new object[] {
                        transactionDb,
                        arrayParameters}, this.setTransactionsArrayOperationCompleted, userState);
        }
        
        private void OnsetTransactionsArrayOperationCompleted(object arg) {
            if ((this.setTransactionsArrayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setTransactionsArrayCompleted(this, new setTransactionsArrayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setImage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string setImage([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] imagen, string rutaFisica, string nombreImagen) {
            object[] results = this.Invoke("setImage", new object[] {
                        imagen,
                        rutaFisica,
                        nombreImagen});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void setImageAsync(byte[] imagen, string rutaFisica, string nombreImagen) {
            this.setImageAsync(imagen, rutaFisica, nombreImagen, null);
        }
        
        /// <remarks/>
        public void setImageAsync(byte[] imagen, string rutaFisica, string nombreImagen, object userState) {
            if ((this.setImageOperationCompleted == null)) {
                this.setImageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetImageOperationCompleted);
            }
            this.InvokeAsync("setImage", new object[] {
                        imagen,
                        rutaFisica,
                        nombreImagen}, this.setImageOperationCompleted, userState);
        }
        
        private void OnsetImageOperationCompleted(object arg) {
            if ((this.setImageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setImageCompleted(this, new setImageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cleanImage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string cleanImage(string rutaFisica, string nombreImagen) {
            object[] results = this.Invoke("cleanImage", new object[] {
                        rutaFisica,
                        nombreImagen});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cleanImageAsync(string rutaFisica, string nombreImagen) {
            this.cleanImageAsync(rutaFisica, nombreImagen, null);
        }
        
        /// <remarks/>
        public void cleanImageAsync(string rutaFisica, string nombreImagen, object userState) {
            if ((this.cleanImageOperationCompleted == null)) {
                this.cleanImageOperationCompleted = new System.Threading.SendOrPostCallback(this.OncleanImageOperationCompleted);
            }
            this.InvokeAsync("cleanImage", new object[] {
                        rutaFisica,
                        nombreImagen}, this.cleanImageOperationCompleted, userState);
        }
        
        private void OncleanImageOperationCompleted(object arg) {
            if ((this.cleanImageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cleanImageCompleted(this, new cleanImageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum TransactionDb {
        
        /// <comentarios/>
        SELECT,
        
        /// <comentarios/>
        UPDATE,
        
        /// <comentarios/>
        INSERT,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ArrayParameters {
        
        private ObjParameters[] objParametersField;
        
        /// <comentarios/>
        public ObjParameters[] objParameters {
            get {
                return this.objParametersField;
            }
            set {
                this.objParametersField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ObjParameters {
        
        private Parameters[] listParametersField;
        
        private string strProcField;
        
        /// <comentarios/>
        public Parameters[] ListParameters {
            get {
                return this.listParametersField;
            }
            set {
                this.listParametersField = value;
            }
        }
        
        /// <comentarios/>
        public string strProc {
            get {
                return this.strProcField;
            }
            set {
                this.strProcField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Parameters {
        
        private string nameField;
        
        private string typeField;
        
        private string sizeField;
        
        private object valueField;
        
        /// <comentarios/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <comentarios/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <comentarios/>
        public string size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <comentarios/>
        public object value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void setTransactionsArrayCompletedEventHandler(object sender, setTransactionsArrayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setTransactionsArrayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setTransactionsArrayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void setImageCompletedEventHandler(object sender, setImageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setImageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setImageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void cleanImageCompletedEventHandler(object sender, cleanImageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cleanImageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cleanImageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591